= Member 조회 APIs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-curl-request-title: 요청 예시
:operation-request-parameters-title: 요청 파라미터
:operation-path-parameters-title: 경로 파라미터
:operation-request-fields-title: 요청 필드
:operation-http-response-title: 결과 예시
:operation-response-fields-title: 결과 필드


== 아이디 존재 여부
operation::member-query-api-doc/is-exists-login-id[snippets='curl-request,request-parameters']
operation::member-query-api-doc/is-exists-login-id[snippets='http-response,response-fields']


== 프로필 조회
operation::member-query-api-doc/get-member-profile[snippets='curl-request,request-parameters']
operation::member-query-api-doc/get-member-profile[snippets='http-response,response-fields']

== 이름 목록 검색
operation::member-query-api-doc/search-nickname[snippets='curl-request,request-parameters']
operation::member-query-api-doc/search-nickname[snippets='http-response,response-fields']

== 아이디 목록 검색
operation::member-query-api-doc/search-login-id[snippets='curl-request,request-parameters']
operation::member-query-api-doc/search-login-id[snippets='http-response,response-fields']